---

- name: Make haproxy bindable on non local addresses
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes
    state: present
  when: haproxy_bind_on_non_local | bool
  tags:
    - haproxy-non-local-bind-config

- name: Drop base haproxy config
  template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/conf.d/00-haproxy"
  notify: Regenerate haproxy configuration
  tags:
    - haproxy-base-config

- name: Drop haproxy logging config
  copy:
    src: "haproxy-logging.cfg"
    dest: "/etc/rsyslog.d/99-haproxy-local-logging.conf"
  notify: Restart rsyslog
  tags:
    - haproxy-logging-config

- include_tasks: haproxy_service_config.yml
  tags:
    - haproxy-service-config
