---

- name: "Create haproxy service config files"
  template:
    src: service.j2
    dest: "/etc/haproxy/conf.d/{{ item.service.haproxy_service_name }}"
  with_items: "{{ haproxy_service_configs | default([]) }}"
  when:
    - (item.service.haproxy_backend_nodes is defined and
      item.service.haproxy_backend_nodes | length > 0) or
      (item.service.haproxy_backup_nodes is defined and
      item.service.haproxy_backup_nodes | length > 0)
    - item.service.haproxy_service_enabled | default('True') | bool
  notify: Regenerate haproxy configuration
  tags:
    - haproxy-service-config

- name: Prevent SELinux from preventing haproxy from binding to arbitrary ports
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  tags:
    - haproxy-service-config
  notify:
    - Restart haproxy
  when:
    - ansible_pkg_mgr == 'yum'
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
