---

- name: Drop user provided ssl cert
  copy:
    src: "{{ haproxy_user_ssl_cert }}"
    dest: "{{ haproxy_ssl_cert }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when: haproxy_user_ssl_cert is defined
  notify:
    - regen pem
  tags:
    - haproxy-ssl

- name: Drop user provided ssl key
  copy:
    src: "{{ haproxy_user_ssl_key }}"
    dest: "{{ haproxy_ssl_key }}"
    owner: "root"
    group: "root"
    mode: "0640"
  when: haproxy_user_ssl_key is defined
  notify:
    - regen pem
  tags:
    - haproxy-ssl

- name: Drop user provided ssl CA cert
  copy:
    src: "{{ haproxy_user_ssl_ca_cert }}"
    dest: "{{ haproxy_ssl_ca_cert }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when: haproxy_user_ssl_ca_cert is defined
  notify:
    - regen pem
  tags:
    - haproxy-ssl
