---

- name: Remove self signed certs and keys for regen
  file:
    dest: "{{ item }}"
    state: "absent"
  with_items:
    - "{{ haproxy_ssl_pem }}"
    - "{{ haproxy_ssl_key }}"
    - "{{ haproxy_ssl_cert }}"
  when: haproxy_ssl_self_signed_regen | bool
  tags:
    - haproxy-ssl

- name: Create self-signed ssl cert
  command: >
    openssl req -new -nodes -sha256 -x509 -subj
    "{{ haproxy_ssl_self_signed_subject }}"
    -days 3650
    -keyout {{ haproxy_ssl_key }}
    -out {{ haproxy_ssl_cert }}
    -extensions v3_ca
    creates={{ haproxy_ssl_cert }}
  notify:
    - regen pem
  tags:
    - haproxy-ssl
