---

- name: Install HAProxy Packages
  package:
    name: "{{ haproxy_distro_packages }}"
    state: "{{ haproxy_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Download HATop
  local_action:
    module: get_url
    url: "{{ haproxy_hatop_download_url }}"
    dest: "/tmp/{{ haproxy_hatop_download_url | basename }}"
    force: yes
    validate_certs: "{{ haproxy_hatop_download_validate_certs }}"
  run_once: True
  vars:
    ansible_python_interpreter: "/usr/bin/python"

- name: Create HATop directory
  file:
    path: "/opt/{{ haproxy_hatop_download_url | basename | replace('.tar.gz', '') }}"
    state: directory

- name: Unarchive HATop
  unarchive:
    src: "/tmp/{{ haproxy_hatop_download_url | basename }}"
    dest: "/opt"

- name: Install HATop
  command: "install -m 755 bin/hatop /usr/local/bin"
  args:
    chdir: "/opt/{{ haproxy_hatop_download_url | basename | replace('.tar.gz', '') }}"
    creates: "/usr/local/bin/hatop"
