---

- name: Ensure the private ssl directory exists
  file:
    dest: "/etc/ssl/private"
    state: "directory"
  tags:
    - haproxy-ssl

- include_tasks: haproxy_ssl_self_signed.yml
  when:
    - haproxy_ssl | bool
    - haproxy_user_ssl_cert is not defined or haproxy_user_ssl_key is not defined

- include_tasks: haproxy_ssl_user_provided.yml
