---

- name: regen pem
  shell: >
    cat {{ haproxy_ssl_cert }} {{ haproxy_user_ssl_ca_cert is defined | ternary(haproxy_ssl_ca_cert,'') }} {{ haproxy_ssl_key }} > {{ haproxy_ssl_pem }}
  notify: Restart haproxy

- name: Regenerate haproxy configuration
  assemble:
    src: "/etc/haproxy/conf.d"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: Restart haproxy
  tags:
    - haproxy-general-config

- name: Restart haproxy
  service:
    name: "haproxy"
    state: "restarted"
    enabled: yes
    daemon_reload: yes

- name: Restart rsyslog
  service:
    name: "rsyslog"
    state: "restarted"
    enabled: yes
    daemon_reload: yes
